# Generated by Django 3.0.2 on 2020-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Creditos', models.PositiveIntegerField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaMatricula', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_partido', models.CharField(max_length=50)),
                ('Pais_partido', models.CharField(max_length=50)),
                ('Ciudad_partido', models.CharField(max_length=50)),
                ('Direccion_partido', models.CharField(max_length=50)),
                ('Zona_partido', models.CharField(max_length=50)),
                ('Inscritos_partido', models.CharField(max_length=4)),
                ('Categoria_partido', models.CharField(max_length=50)),
                ('Inicio_partido', models.DateField()),
                ('Fin_partido', models.DateField()),
                ('Primer_partido', models.CharField(max_length=8)),
                ('Segundo_partido', models.CharField(max_length=8)),
                ('Tercero_partido', models.CharField(max_length=8)),
                ('Cuarto_partido', models.CharField(max_length=8)),
                ('Goleador_partido', models.CharField(max_length=4)),
                ('Guante_partido', models.CharField(max_length=4)),
                ('Caracteristica_partido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posicion_resultado', models.CharField(max_length=50)),
                ('Pj_resultado', models.CharField(max_length=3)),
                ('Pg_resultado', models.CharField(max_length=3)),
                ('Pe_resultado', models.CharField(max_length=3)),
                ('Pp_resultado', models.CharField(max_length=3)),
                ('Gf_resultado', models.CharField(max_length=3)),
                ('Gc_resultado', models.CharField(max_length=3)),
                ('Gd_resultado', models.CharField(max_length=3)),
                ('Pt_resultado', models.CharField(max_length=3)),
                ('Nombres', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
    ]
