# Generated by Django 3.0.2 on 2020-02-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEncuentros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Torneo_Horario', models.CharField(max_length=4)),
                ('Fecha_Partido', models.DateField()),
                ('Hora_Partido', models.DateField()),
                ('Estado', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], default='L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_partido', models.CharField(max_length=50)),
                ('Pais_partido', models.CharField(max_length=50)),
                ('Ciudad_partido', models.CharField(max_length=50)),
                ('Grupo_partido', models.CharField(max_length=50)),
                ('Equipo_Local_partido', models.CharField(max_length=4)),
                ('Equipo_Vesitante_partido', models.CharField(max_length=4)),
                ('Fecha_partido', models.DateField()),
                ('Campo_partido', models.CharField(max_length=50)),
                ('Gol_Local_partido', models.CharField(max_length=4)),
                ('Gol_Visitante_partido', models.CharField(max_length=4)),
                ('Goleador_partido', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Torneo_Resultado', models.CharField(max_length=4)),
                ('Fecha_Resultado', models.DateField()),
                ('Equipo_Resultado', models.CharField(max_length=4)),
                ('Posicion_resultado', models.CharField(max_length=50)),
                ('Pj_resultado', models.CharField(max_length=3)),
                ('Pg_resultado', models.CharField(max_length=3)),
                ('Pe_resultado', models.CharField(max_length=3)),
                ('Pp_resultado', models.CharField(max_length=3)),
                ('Gf_resultado', models.CharField(max_length=3)),
                ('Gc_resultado', models.CharField(max_length=3)),
                ('Gd_resultado', models.CharField(max_length=3)),
                ('Pt_resultado', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Sancion', models.DateField()),
                ('FechaMatricula', models.DateField(auto_now_add=True)),
                ('Tipo', models.CharField(choices=[('A', 'Amarilla'), ('R', 'Roja')], default='A', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Partidos',
        ),
        migrations.DeleteModel(
            name='Resultados',
        ),
    ]
