# Generated by Django 3.0.2 on 2020-02-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Creditos', models.PositiveIntegerField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_equipo', models.CharField(max_length=50)),
                ('Pais_equipo', models.CharField(max_length=50)),
                ('Ciudad_equipo', models.CharField(max_length=50)),
                ('Escudo_equipo', models.CharField(max_length=50)),
                ('Direccion_equipo', models.CharField(max_length=50)),
                ('Uniforme_equipo', models.CharField(max_length=50)),
                ('Telefono_equipo', models.CharField(max_length=8)),
                ('Descripcion_equipo', models.CharField(max_length=200)),
                ('Nombres', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_torneo', models.CharField(max_length=8)),
                ('Nombre_torneo', models.CharField(max_length=50)),
                ('Tipo_torneo', models.CharField(max_length=50)),
                ('Pais_torneo', models.CharField(max_length=50)),
                ('Ciudad_torneo', models.CharField(max_length=50)),
                ('Direccion_torneo', models.CharField(max_length=50)),
                ('Zona_torneo', models.CharField(max_length=50)),
                ('Inscritos_torneo', models.CharField(max_length=4)),
                ('Categoria_torneo', models.CharField(max_length=50)),
                ('Inicio_torneo', models.DateField()),
                ('Fin_torneo', models.DateField()),
                ('Primer_torneo', models.CharField(max_length=8)),
                ('Segundo_torneo', models.CharField(max_length=8)),
                ('Tercero_torneo', models.CharField(max_length=8)),
                ('Cuarto_torneo', models.CharField(max_length=8)),
                ('Goleador_torneo', models.CharField(max_length=4)),
                ('Guante_torneo', models.CharField(max_length=4)),
                ('Caracteristica_torneo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaMatricula', models.DateField(auto_now_add=True)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLiga.Curso')),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLiga.Equipo')),
            ],
        ),
    ]
