# Generated by Django 3.0.2 on 2020-02-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLiga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Deporte', models.CharField(max_length=50)),
                ('Tipo_Deporte', models.CharField(choices=[('I', 'Individual'), ('G', 'Grupal')], default='G', max_length=1)),
                ('Cantidad_Deporte', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Grupo', models.CharField(max_length=50)),
                ('Torneo_Grupo', models.PositiveIntegerField()),
                ('Estado_Grupo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_torneo', models.CharField(max_length=50)),
                ('Tipo_torneo', models.CharField(max_length=50)),
                ('Pais_torneo', models.CharField(max_length=50)),
                ('Ciudad_torneo', models.CharField(max_length=50)),
                ('Direccion_torneo', models.CharField(max_length=50)),
                ('Zona_torneo', models.CharField(max_length=50)),
                ('Inscritos_torneo', models.CharField(max_length=4)),
                ('Categoria_torneo', models.CharField(max_length=50)),
                ('Inicio_torneo', models.DateField()),
                ('Fin_torneo', models.DateField()),
                ('Primer_torneo', models.CharField(max_length=8)),
                ('Segundo_torneo', models.CharField(max_length=8)),
                ('Tercero_torneo', models.CharField(max_length=8)),
                ('Cuarto_torneo', models.CharField(max_length=8)),
                ('Goleador_torneo', models.CharField(max_length=4)),
                ('Guante_torneo', models.CharField(max_length=4)),
                ('Caracteristica_torneo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Torneos',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Descripcion_equipo',
            new_name='Descripcion_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Direccion_equipo',
            new_name='Direccion_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Escudo_equipo',
            new_name='Dueno_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Nombre_equipo',
            new_name='Escudo_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Nombres',
            new_name='Nombre_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Pais_equipo',
            new_name='Pais_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Telefono_equipo',
            new_name='Telefono_Equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Uniforme_equipo',
            new_name='Uniforme_Equipo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.AddField(
            model_name='grupo',
            name='Nombre_Equipo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLiga.Equipo'),
        ),
    ]
